<?php
function spipr_educ_definition_graphisme() {
	$def = array(
		'graphisme_marges'=>array('graphisme_marges','graphisme'),
		'graphisme_couleur_textes'=>array('graphisme_couleur_textes','graphisme'),
		'graphisme_couleur_fond'=>array('graphisme_couleur_fond','graphisme'),
		'graphisme_typographie'=>array('graphisme_typographie','graphisme'),
		'graphisme_tableaux'=>array('graphisme_tableaux','graphisme'),
		'graphisme_pagination'=>array('graphisme_pagination','graphisme'),
		'graphisme_fil_ariane'=>array('graphisme_fil_ariane','graphisme'),
		'graphisme_menu_horizontal'=>array('graphisme_menu_horizontal','graphisme'),
		'graphisme_menu_deroulant'=>array('graphisme_menu_deroulant','graphisme'),
		'graphisme_menu_icones'=>array('graphisme_menu_icones','graphisme'),
		'graphisme_editorial_hero'=>array('graphisme_editorial_hero','graphisme'),
		'graphisme_carousel'=>array('graphisme_carousel','graphisme'),
		'graphisme_carousel_2'=>array('graphisme_carousel_2','graphisme'),
		'graphisme_menu_vertical'=>array('graphisme_menu_vertical','graphisme'),
		'graphisme_css'=>array('graphisme_css','graphisme'),
		'graphisme_bloc_logos'=>array('graphisme_bloc_logos','graphisme'),
		'graphisme_liens_partenaires'=>array('graphisme_liens_partenaires','graphisme'),
		'graphisme_formulaires'=>array('graphisme_formulaires','graphisme'),
		'sommaire_bloc_perso_1'=>array('sommaire_bloc_perso_1','graphisme'),
		'sommaire_bloc_perso_2'=>array('sommaire_bloc_perso_2','graphisme'),
		'sommaire_bloc_perso_3'=>array('sommaire_bloc_perso_3','graphisme'),
		'sommaire_compteur'=>array('sommaire_compteur','graphisme'),
		'article_bloc_perso_1'=>array('article_bloc_perso_1','graphisme'),
		'article_bloc_perso_2'=>array('article_bloc_perso_2','graphisme'),
		'article_bloc_perso_3'=>array('article_bloc_perso_3','graphisme'),
		'article_compteur'=>array('article_compteur','graphisme'),
		'rubrique_bloc_perso_1'=>array('rubrique_bloc_perso_1','graphisme'),
		'rubrique_bloc_perso_2'=>array('rubrique_bloc_perso_2','graphisme'),
		'rubrique_bloc_perso_3'=>array('rubrique_bloc_perso_3','graphisme'),
		'breve_bloc_perso_1'=>array('breve_bloc_perso_1','graphisme'),
		'breve_bloc_perso_2'=>array('breve_bloc_perso_2','graphisme'),
		'breve_bloc_perso_3'=>array('breve_bloc_perso_3','graphisme'),
		'site_bloc_perso_1'=>array('site_bloc_perso_1','graphisme'),
		'site_bloc_perso_2'=>array('site_bloc_perso_2','graphisme'),
		'site_bloc_perso_3'=>array('site_bloc_perso_3','graphisme'),
		'auteur_bloc_perso_1'=>array('auteur_bloc_perso_1','graphisme'),
		'auteur_bloc_perso_2'=>array('auteur_bloc_perso_2','graphisme'),
		'auteur_bloc_perso_3'=>array('auteur_bloc_perso_3','graphisme'),
		'autre_bloc_perso_1'=>array('autre_bloc_perso_1','graphisme'),
		'autre_bloc_perso_2'=>array('autre_bloc_perso_2','graphisme'),
		'autre_bloc_perso_3'=>array('autre_bloc_perso_3','graphisme'),
		'fond_ecran'=>array('fond_ecran','graphisme'),
		'fond_page'=>array('fond_page','graphisme'),
		'fond_entete'=>array('fond_entete','graphisme'),
		'fond_barre_menu'=>array('fond_barre_menu','graphisme'),
		'fond_breadcrumb'=>array('fond_breadcrumb','graphisme'),
		'fond_pied'=>array('fond_pied','graphisme'),
		'options_sites'=>array('options_sites','gestion bloc'),
		'options_rubriques'=>array('options_rubriques','gestion bloc'),
		'options_articles'=>array('options_articles','gestion bloc'),
	);
	return $def;	
}
?>