bandeau:
 -
  posban: '300'
  remplissant: non
  tbandeau: non
blocs:
 -
  menu: '2'
  date_article: oui
  auteurs: oui
  intit_script: titre
  add_script: ''
boutons:
 -
  1:
    intit: ''
    add: 'http://www.ac-creteil.fr/'
    blanck: blanck
    emplacement: bandeau
    boutonimage: IMG/config/boutons/image_b2.png
    alt: 'Education nationale'
  2:
    intit: ENT
    add: 'http://www.mon-ent.fr'
    blanck: null
    emplacement: colonne_d
    alt: ''
couleurs:
 -
  bandeau: '#0f0068'
  bandtex: '#ffffff'
  chemtex: '#000000'
  pfond: '#ffffff'
  chemin: '#e0e7ff'
  bordchemin: '#d3e1e8'
  textg: '#000000'
  lienmen: '#000f98'
  liensur: '#000f0e'
  textemenu: ' #ffffff'
  lien: '#036d11'
  fondtexte: '#ffffff'
  bord: '#ccc7c7'
  texte: '#000000'
  bandeauagenda: '#d7d6d6'
  textebandeau: '#ffffff'
  texteagenda: '#000000'
  fondagenda: '#ffffff'
  bordagenda: '#000000'
  lienagenda: '#09229f'
  lienagendasurvol: '#017548'
  fondbouton: '#b8c2d5'
  fondboutonhover: '#879cc5'
  bordbouton: '#000000'
  textebouton: '#ffffff'
  bgmenu: '#ffffff'
  bgmenusur: '#ffffff'
mentions:
 -
  dir: '1'
  master: '5'
  entete: titre
  intitule1: titre
  valeur1: titre
sommaire:
 -
  choixsom: '1'
  y:
    1: aucun
    2: aucun
    3: aucun
    4: aucun
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  x:
    1: boutons_accueil
    2: edito
    3: focus
    4: derniers_articles
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
squelettes:
 -
  style: layout1.css
  d:
    1: formulaire_recherche
    2: logo
    3: boutons_droite
    4: breves
    5: sites_favoris
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  g:
    1: menu
    2: boutons_gauche
    3: bouton_plan
    4: mise_a_jour
    5: mentions_legales
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  skel:
    skels1: articles_plus_lus
    skels2: boutons_accueil
    skels3: boutons_droite
    skels4: boutons_gauche
    skels5: bouton_blog
    skels6: bouton_forum
    skels7: bouton_plan
    skels8: breves
    skels9: carte
    skels10: derniers_articles
    skels11: diaporama
    skels12: edito
    skels13: focus
    skels14: formulaire_recherche
    skels15: logo
    skels16: mentions_legales
    skels17: menu
    skels18: mini_agenda
    skels19: mise_a_jour
    skels20: nuage
    skels21: sites_academiques
    skels22: sites_favoris
    skels23: s_identifier
rubriques:
 -
  skel:
    skels1: rubrique_2col_complet
    skels2: rubrique_1col_complet
    skels3: articles_rubrique
    skels4: sous_rubriques
    skels5: rubrique_2col_simple
    skels6: rubrique_1col_simple
  effectifs:
    1: rubrique_2col_simple
    2: aucun
    3: aucun
    4: aucun
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
chemin:
 -
  effectifs:
    1: traits_chemin
    2: onglets
    3: fil_ariane
    4: aucun
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  skel:
    skels1: bandeau_reseau
    skels2: fil_ariane
    skels3: onglets
    skels4: traits_chemin
footer:
 -
  effectifs:
    1: datice_footer
    2: aucun
    3: aucun
    4: aucun
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  skel:
    skels1: datice_footer
articles:
 -
  effectifs:
    1: article_complet
    2: aucun
    3: aucun
    4: aucun
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  skel:
    skels1: article_complet
mobil:
 -
  effectifs:
    1: formulaire_recherche
    2: focus
    3: derniers_articles
    4: menu
    5: aucun
    6: aucun
    7: aucun
    8: aucun
    9: aucun
    10: aucun
    11: aucun
    12: aucun
  skel:
    skels1: menu
    skels2: formulaire_recherche
    skels3: derniers_articles
    skels4: edito
    skels5: breves
    skels6: focus
images:
 -
rechavancee:
 -
nuage:
 -