<?php
// Pensez, si vous modifiez ce message, a convertir les caracteres etendus
// en entites HTML pour eviter les problemes d'affichage.
?>
<p>
Pensez &agrave; donner un <strong>titre</strong> &agrave; votre article. Le titre &laquo;Nouvel article&nbsp;&raquo;, 
&ccedil;a n&#39;est pas tr&egrave;s all&egrave;chant !
</p>

<p>
Pensez aussi &agrave; s&eacute;lectionner une <strong>rubrique</strong> 
dans laquelle votre article sera class&eacute;. 
Sans cela, il n&rsquo;appara&icirc;tra pas &agrave; sa place dans le site. 
Le choix d&rsquo;une rubrique se fait en cliquant sur l&rsquo;ic&ocirc;ne <img src="/dist/images/loupe.png" alt="loupe"> 
qu&rsquo;on trouve apr&egrave;s la mention &laquo;&nbsp;&Agrave; l&rsquo;int&eacute;rieur de la rubrique&nbsp;&raquo;.
</p>
